# Generated by Django 5.0.5 on 2024-05-07 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('subTitle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=10)),
                ('image_url', models.URLField(validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
